from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

# Output/result directories generated by runs/backtests.
OUTPUT_DIRS = {
    "output",
    "outputs",
    "output_debug",
    "output_tmp_check",
    "output_tmp_check2",
    "backtests",
    "results",
    "reports",
    "dist",
    "build",
}

# Cache directories.
CACHE_DIRS = {
    "__pycache__",
    ".pytest_cache",
    ".cache",
    "cache",
}

# Cached artifact files.
CACHE_FILE_SUFFIXES = {".pkl", ".pickle", ".parquet", ".feather", ".joblib"}


def _safe_rmtree(path: Path) -> bool:
    if not path.exists():
        return False
    if path.is_dir():
        shutil.rmtree(path)
        return True
    return False


def _safe_unlink(path: Path) -> bool:
    if not path.exists() or path.is_dir():
        return False
    path.unlink()
    return True


def clean_workspace() -> tuple[list[Path], list[Path]]:
    removed_dirs: list[Path] = []
    removed_files: list[Path] = []

    # 1) Remove known output directories at repository root.
    for name in sorted(OUTPUT_DIRS):
        candidate = ROOT / name
        if _safe_rmtree(candidate):
            removed_dirs.append(candidate)

    # 2) Remove cache directories recursively.
    for path in ROOT.rglob("*"):
        if not path.is_dir():
            continue
        if path.name in CACHE_DIRS:
            # Keep VCS and data assets untouched by only removing directory caches.
            if _safe_rmtree(path):
                removed_dirs.append(path)

    # 3) Remove cache artifact files recursively, excluding data/config folders.
    protected_roots = {ROOT / "data", ROOT / "configs"}
    for path in ROOT.rglob("*"):
        if path.is_dir():
            continue
        if any(parent in protected_roots for parent in [path] + list(path.parents)):
            continue
        if path.suffix.lower() in CACHE_FILE_SUFFIXES:
            if _safe_unlink(path):
                removed_files.append(path)

    return removed_dirs, removed_files


def main() -> int:
    removed_dirs, removed_files = clean_workspace()
    print(f"CLEAN SUMMARY | removed_dirs={len(removed_dirs)} | removed_files={len(removed_files)}")
    for path in removed_dirs:
        print(f"DIR_REMOVED {path}")
    for path in removed_files:
        print(f"FILE_REMOVED {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
